name: Deploy App to EKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: false
        default: "latest"
  push:
    branches: [main]
    paths:
      - "k8s/base/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: arc-runner-set-app
    steps:
      - uses: actions/checkout@v4

      - name: Instalar kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Using a local cluster
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Create namespace
        run: kubectl create namespace app --dry-run=client -o yaml | kubectl apply -f -

      - name: Set image tag
        run: |
          TAG="${{ github.event.inputs.image_tag || github.sha }}"
          sed -i "s|julianareiza/app-ge:.*|julianareiza/app-ge:${TAG}|g" k8s/base/deployment.yml

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/base/

      - name: Wait for rollout
        run: kubectl rollout status deployment/app-ge -n app --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -n app -l app=app-ge
          kubectl get svc -n app
