name: Deploy OTel Collector

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "k8s/otel-collector/**"

# env:
#   AWS_REGION: ${{ secrets.AWS_REGION }}
#   EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy:
    name: Deploy OTel Collector
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Instalar kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy OTel Collector
        run: kubectl apply -f k8s/otel-collector/

      - name: Wait for rollout
        run: kubectl rollout status deployment/otel-collector -n observability --timeout=120s

      - name: Verify
        run: kubectl get pods -n observability -l app=otel-collector
